# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Acrylicorner
email: holdenprofit at gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blogsite and portfolio of Holden Profit, web developer and game developer!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acrylicorner.com" # the base hostname & protocol for your site
twitter_username: h_profit
github_username:  hprofit

# Build settings
markdown: kramdown
