# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Holden Profit
email: holdenprofit at gmail.com
description: The personal blogsite and portfolio of Holden Profit - game developer, hobby artist, and aspiring car enthusiast!
baseurl: "" # the subpath of your site, e.g. /blog
url: http://holdenprofit.com # the base hostname & protocol for your site
#url: http://localhost:4000 #local dev only

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: hprofit
  twitter: h_profit
  linkedin: holden-profit
  rss: feed.xml

twitter_username: h_profit

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-113567099-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: holdenprofit-com
comments: true

# permalink: /:year/:month/:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']

presentations: [
  ['swarmIntelligence.html', 'Swarm Intelligence'],
  ['howToUseGit.html', 'How to Use Git'],
  ['howToUseJasmine.html', 'How to Use Jasmine'],
  ['introToGaming_part1.html', 'Introduction to Game Development Part 1'],
  ['introToGaming_part2.html', 'Introduction to Game Development Part 2'],
  ['introToGaming_part3.html', 'Introduction to Game Development Part 3'],
  ['introToGaming_part4.html', 'Introduction to Game Development Part 4']
]
